/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author User
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RBalok = new javax.swing.JRadioButton();
        RKubus = new javax.swing.JRadioButton();
        RSegitiga = new javax.swing.JRadioButton();
        RTrapesium = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jDesktopPane12 = new javax.swing.JDesktopPane();
        PanelBalok11 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        volumeBalok11 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        hasilBalok11 = new javax.swing.JLabel();
        PBalok11 = new javax.swing.JTextField();
        LBalok11 = new javax.swing.JTextField();
        TBalok11 = new javax.swing.JTextField();
        panelKubus = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        volumeKubus = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        hasilKubus = new javax.swing.JLabel();
        Sisi1 = new javax.swing.JTextField();
        Sisi2 = new javax.swing.JTextField();
        Sisi3 = new javax.swing.JTextField();
        PanelSegitiga = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        luasSegitiga = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        hasilSegitiga = new javax.swing.JLabel();
        alas = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        PanelTrapesium = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        LuasTrapesium = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        hasilTrapesium = new javax.swing.JLabel();
        AtasTrapesium = new javax.swing.JTextField();
        BawahTrapesium = new javax.swing.JTextField();
        TinggiTrapesium = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Hitung Bangun Datar dan Bangun Ruang");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RBalok.setText("Volume Balok");

        RKubus.setText("Volume Kubus");

        RSegitiga.setText("Luas Segitiga");

        RTrapesium.setText("Luas Trapesium");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Program Hitung Bangun Datar dan Bangun Ruang");

        PanelBalok11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volume Balok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel47.setText("Panjang");

        jLabel48.setText("Lebar");

        jLabel49.setText("Tinggi");

        volumeBalok11.setText("Hitung");
        volumeBalok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeBalok11ActionPerformed(evt);
            }
        });

        jLabel50.setText("Volume");

        hasilBalok11.setText("0");

        TBalok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBalok11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBalok11Layout = new javax.swing.GroupLayout(PanelBalok11);
        PanelBalok11.setLayout(PanelBalok11Layout);
        PanelBalok11Layout.setHorizontalGroup(
            PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBalok11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBalok11Layout.createSequentialGroup()
                        .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeBalok11)
                            .addGroup(PanelBalok11Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(18, 18, 18)
                                .addComponent(hasilBalok11)))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(PanelBalok11Layout.createSequentialGroup()
                        .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TBalok11)
                            .addComponent(LBalok11)
                            .addComponent(PBalok11))))
                .addContainerGap())
        );
        PanelBalok11Layout.setVerticalGroup(
            PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBalok11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(PBalok11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(LBalok11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(TBalok11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volumeBalok11)
                .addGap(18, 18, 18)
                .addGroup(PanelBalok11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(hasilBalok11)))
        );

        panelKubus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volume Kubus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel51.setText("Sisi");

        jLabel52.setText("Sisi");

        jLabel53.setText("Sisi");

        volumeKubus.setText("Hitung");

        jLabel54.setText("Volume");

        hasilKubus.setText("0");

        Sisi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sisi3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKubusLayout = new javax.swing.GroupLayout(panelKubus);
        panelKubus.setLayout(panelKubusLayout);
        panelKubusLayout.setHorizontalGroup(
            panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKubusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeKubus)
                    .addGroup(panelKubusLayout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(18, 18, 18)
                        .addComponent(hasilKubus))
                    .addGroup(panelKubusLayout.createSequentialGroup()
                        .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Sisi2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(Sisi3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sisi1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKubusLayout.setVerticalGroup(
            panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKubusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(Sisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(Sisi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(Sisi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volumeKubus)
                .addGap(18, 18, 18)
                .addGroup(panelKubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(hasilKubus)))
        );

        PanelSegitiga.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Luas Segitiga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel55.setText("Alas");

        jLabel56.setText("Tinggi");

        luasSegitiga.setText("Hitung");

        jLabel57.setText("Luas");

        hasilSegitiga.setText("0");

        javax.swing.GroupLayout PanelSegitigaLayout = new javax.swing.GroupLayout(PanelSegitiga);
        PanelSegitiga.setLayout(PanelSegitigaLayout);
        PanelSegitigaLayout.setHorizontalGroup(
            PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSegitigaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luasSegitiga)
                    .addGroup(PanelSegitigaLayout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addComponent(hasilSegitiga))
                    .addGroup(PanelSegitigaLayout.createSequentialGroup()
                        .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tinggi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(alas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSegitigaLayout.setVerticalGroup(
            PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSegitigaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(luasSegitiga)
                .addGap(42, 42, 42)
                .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(hasilSegitiga)))
        );

        PanelTrapesium.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Luas Trapesium", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel58.setText("Atas");

        jLabel59.setText("Bawah");

        LuasTrapesium.setText("Hitung");

        jLabel60.setText("Luas");

        hasilTrapesium.setText("0");

        jLabel61.setText("Tinggi");

        javax.swing.GroupLayout PanelTrapesiumLayout = new javax.swing.GroupLayout(PanelTrapesium);
        PanelTrapesium.setLayout(PanelTrapesiumLayout);
        PanelTrapesiumLayout.setHorizontalGroup(
            PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTrapesiumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LuasTrapesium)
                    .addGroup(PanelTrapesiumLayout.createSequentialGroup()
                        .addComponent(jLabel60)
                        .addGap(18, 18, 18)
                        .addComponent(hasilTrapesium))
                    .addGroup(PanelTrapesiumLayout.createSequentialGroup()
                        .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BawahTrapesium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(AtasTrapesium)
                            .addComponent(TinggiTrapesium))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTrapesiumLayout.setVerticalGroup(
            PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTrapesiumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(AtasTrapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(BawahTrapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinggiTrapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61))
                .addGap(18, 18, 18)
                .addComponent(LuasTrapesium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTrapesiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(hasilTrapesium)))
        );

        jDesktopPane12.setLayer(PanelBalok11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(panelKubus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(PanelSegitiga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(PanelTrapesium, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane12Layout = new javax.swing.GroupLayout(jDesktopPane12);
        jDesktopPane12.setLayout(jDesktopPane12Layout);
        jDesktopPane12Layout.setHorizontalGroup(
            jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBalok11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTrapesium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane12Layout.setVerticalGroup(
            jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTrapesium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSegitiga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKubus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBalok11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(RTrapesium)
                .addGap(18, 18, 18)
                .addComponent(RSegitiga)
                .addGap(18, 18, 18)
                .addComponent(RBalok)
                .addGap(18, 18, 18)
                .addComponent(RKubus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RTrapesium)
                    .addComponent(RSegitiga)
                    .addComponent(RBalok)
                    .addComponent(RKubus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane12)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // VOLUME BALOK
    private void volumeBalok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeBalok11ActionPerformed
        // TODO add your handling code here:
        int p, l, t;
        double v;
        p = Integer.parseInt(PBalok11.getText());
        l = Integer.parseInt(LBalok11.getText());
        t = Integer.parseInt(TBalok11.getText());
        v = p*l*t;
        hasilBalok11.setText("" + v);
    }//GEN-LAST:event_volumeBalok11ActionPerformed
    
    // VOLUME KUBUS
    private void volumeKubusActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        float s1, s2, s3, v;
        s1 = Float.parseFloat(sisi1.getText());
        s2 = Float.parseFloat(Sisi2.getText());
        s3 = Float.parseFloat(Sisi3.getText());
        
        v = s1 * s2 * s3;
        hasilKubus.setText("" + v );
    } 
    
    // LUAS SEGITIGA
    private void luasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        float a, t, L;
        a = Float.parseFloat(alas.getText());
        t = Float.parseFloat(tinggi.getText());
        
        L = a*t/2;
        hasilSegitiga.setText(""+L);
    }
    
    // LUAS TRAPESIUM
    private void LuasTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        float a, b, L;
        a = Float.parseFloat(AtasTrapesium.getText());
        b = Float.parseFloat(BawahTrapesium.getText());
        
        L = (a+b)/2;
        hasilTrapesium.setText("" + L);
    }
    
    private void TBalok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBalok11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBalok11ActionPerformed

    private void Sisi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sisi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sisi3ActionPerformed
    
    // FUNGSI RADIO BUTTON TRAPESIUM
    private void RTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if(this.RTrapesium.isSelected()){
            this.PanelTrapesium.setVisible(true);
            this.PanelSegitiga.setVisible(false);
            this.PanelBalok11.setVisible(false);
            this.panelKubus.setVisible(false);
        }else{
            this.PanelTrapesium.setVisible(false);
        }
    }
    
    // FUNGSI RADIO BUTTON SEGITIGA
    private void RSegitigaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(this.RSegitiga.isSelected()){
            this.PanelSegitiga.setVisible(true);
            this.PanelBalok11.setVisible(false);
            this.panelKubus.setVisible(false);
            this.PanelTrapesium.setVisible(false);
        }else{
            this.PanelSegitiga.setVisible(false);
        }
    }
    
    // FUNGSI RADIO BUTTON BALOK
    private void RBalokActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(!this.RBalok.isSelected()){
            this.PanelBalok11.setVisible(false);
        }else{
            this.PanelBalok11.setVisible(true);
            this.panelKubus.setVisible(false);
            this.PanelSegitiga.setVisible(false);
            this.PanelTrapesium.setVisible(false);
        }
    }
    
    // FUNGSI RADIO BUTTON KUBUS
    private void RKubusActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(this.RKubus.isSelected()){
            this.panelKubus.setVisible(true);
            this.PanelBalok.setVisible(false);
            this.PanelSegitiga.setVisible(false);
            this.PanelTrapesium.setVisible(false);
        }else{
            this.panelKubus.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AtasTrapesium;
    private javax.swing.JTextField BawahTrapesium;
    private javax.swing.JTextField LBalok;
    private javax.swing.JTextField LBalok1;
    private javax.swing.JTextField LBalok10;
    private javax.swing.JTextField LBalok11;
    private javax.swing.JTextField LBalok2;
    private javax.swing.JTextField LBalok3;
    private javax.swing.JTextField LBalok4;
    private javax.swing.JTextField LBalok5;
    private javax.swing.JTextField LBalok6;
    private javax.swing.JTextField LBalok7;
    private javax.swing.JTextField LBalok8;
    private javax.swing.JTextField LBalok9;
    private javax.swing.JButton LuasTrapesium;
    private javax.swing.JTextField PBalok;
    private javax.swing.JTextField PBalok1;
    private javax.swing.JTextField PBalok10;
    private javax.swing.JTextField PBalok11;
    private javax.swing.JTextField PBalok2;
    private javax.swing.JTextField PBalok3;
    private javax.swing.JTextField PBalok4;
    private javax.swing.JTextField PBalok5;
    private javax.swing.JTextField PBalok6;
    private javax.swing.JTextField PBalok7;
    private javax.swing.JTextField PBalok8;
    private javax.swing.JTextField PBalok9;
    private javax.swing.JPanel PanelBalok;
    private javax.swing.JPanel PanelBalok1;
    private javax.swing.JPanel PanelBalok10;
    private javax.swing.JPanel PanelBalok11;
    private javax.swing.JPanel PanelBalok2;
    private javax.swing.JPanel PanelBalok3;
    private javax.swing.JPanel PanelBalok4;
    private javax.swing.JPanel PanelBalok5;
    private javax.swing.JPanel PanelBalok6;
    private javax.swing.JPanel PanelBalok7;
    private javax.swing.JPanel PanelBalok8;
    private javax.swing.JPanel PanelBalok9;
    private javax.swing.JPanel PanelSegitiga;
    private javax.swing.JPanel PanelTrapesium;
    private javax.swing.JRadioButton RBalok;
    private javax.swing.JRadioButton RKubus;
    private javax.swing.JRadioButton RSegitiga;
    private javax.swing.JRadioButton RTrapesium;
    private javax.swing.JTextField Sisi1;
    private javax.swing.JTextField Sisi2;
    private javax.swing.JTextField Sisi3;
    private javax.swing.JTextField TBalok;
    private javax.swing.JTextField TBalok1;
    private javax.swing.JTextField TBalok10;
    private javax.swing.JTextField TBalok11;
    private javax.swing.JTextField TBalok2;
    private javax.swing.JTextField TBalok3;
    private javax.swing.JTextField TBalok4;
    private javax.swing.JTextField TBalok5;
    private javax.swing.JTextField TBalok6;
    private javax.swing.JTextField TBalok7;
    private javax.swing.JTextField TBalok8;
    private javax.swing.JTextField TBalok9;
    private javax.swing.JTextField TinggiTrapesium;
    private javax.swing.JTextField alas;
    private javax.swing.JLabel hasilBalok;
    private javax.swing.JLabel hasilBalok1;
    private javax.swing.JLabel hasilBalok10;
    private javax.swing.JLabel hasilBalok11;
    private javax.swing.JLabel hasilBalok2;
    private javax.swing.JLabel hasilBalok3;
    private javax.swing.JLabel hasilBalok4;
    private javax.swing.JLabel hasilBalok5;
    private javax.swing.JLabel hasilBalok6;
    private javax.swing.JLabel hasilBalok7;
    private javax.swing.JLabel hasilBalok8;
    private javax.swing.JLabel hasilBalok9;
    private javax.swing.JLabel hasilKubus;
    private javax.swing.JLabel hasilSegitiga;
    private javax.swing.JLabel hasilTrapesium;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane10;
    private javax.swing.JDesktopPane jDesktopPane11;
    private javax.swing.JDesktopPane jDesktopPane12;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton luasSegitiga;
    private javax.swing.JPanel panelKubus;
    private javax.swing.JTextField tinggi;
    private javax.swing.JButton volumeBalok;
    private javax.swing.JButton volumeBalok1;
    private javax.swing.JButton volumeBalok10;
    private javax.swing.JButton volumeBalok11;
    private javax.swing.JButton volumeBalok2;
    private javax.swing.JButton volumeBalok3;
    private javax.swing.JButton volumeBalok4;
    private javax.swing.JButton volumeBalok5;
    private javax.swing.JButton volumeBalok6;
    private javax.swing.JButton volumeBalok7;
    private javax.swing.JButton volumeBalok8;
    private javax.swing.JButton volumeBalok9;
    private javax.swing.JButton volumeKubus;
    // End of variables declaration//GEN-END:variables
}
